=== adrianEP474/103LMSGIProyectoLMSGI/103LMSGIProyectoLMSGI/ud4/p2/02.dtd
<!ELEMENT biblio (libro)+>
<!ELEMENT libro (titulo,autores,anyo)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (nombre, apellido, nacionalidad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ATTLIST libro idlibro ID #REQUIRED>
<!ATTLIST libro genero CDATA #IMPLIED>
<!ATTLIST libro formato (impreso|digital)>
<!ATTLIST libro ref IDREFS #IMPLIED>

=== adrianEP474/103LMSGIProyectoLMSGI/103LMSGIProyectoLMSGI/ud4/p2/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblio SYSTEM '02.dtd'>
<biblio>
    <libro idlibro="libro1" genero="Accion" ref="libro1">
        <titulo>Harry Potter</titulo>
        <autores>
            <autor>
                <nombre>Agata</nombre>
                <apellido>Cristi</apellido>
                <nacionalidad>Nigeriana</nacionalidad>
            </autor>
        </autores>
        <anyo>2019</anyo>
    </libro>
    <libro idlibro="libro2" genero="Accion">
        <titulo>Ana Frank</titulo>
        <autores>
            <autor>
                <nombre>Ana</nombre>
                <apellido>Frank</apellido>
                <nacionalidad>Bulgara</nacionalidad>
            </autor>
        </autores>
        <anyo>1945</anyo>
    </libro>
</biblio>
